In [49]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [50]:
tf.__version__

'2.12.0'

## Part 1- Data Preprocessing

### Importing the dataset

In [51]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [52]:
print(x[0])

[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]


In [53]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding the Categorical data

##### Label Encoding the "Gender" column (relationship)


In [54]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [55]:
(x)

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

##### One Hot Encoding the "Geography" column (no relationship) {eg: 100-france, 001-spain, 010-germany}

In [48]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))
x[0]

array([1.0, 0.0, 1.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

### Splitting the dataset into the Training set and Testing set

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

### Feature Scaling {compulsary for deep learning}

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

## Part 2 - Building the ANN

### Initializing ANN

In [24]:
ann = tf.keras.models.Sequential()
#this Sequential() is taken from models module from the keras library which since tensorflow 2.0
#belongs to tensorflow keras is integrated therefore, tf.keras.models.Sequential class
#this ann object initializes our artificial neural network as a sequence of layers

### Adding the input layer and the first hidden layer

In [25]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))
#the add method can add the any hidden layers
#fully connected layer we are going to build will be an object of the dense class
#And it automatically add the input layer
#layers is the module that has classes to add any layer we want in our ANN
#units is no.of neurons(hidden neurons) we want to add in the first layer
#(like from credit_score column as one input neuron and so on all columns as different neurons )

### Adding the input layer and the Second hidden layer

In [26]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))
#Dense helps to connect to 1st input layer fully(now)

### Adding the output layer

In [28]:
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))
#Because for sigmoid activation function we get probability too for the output

## Part 3 - Training the ANN

### Compiling the ANN

In [31]:
ann.compile(optimizer = 'Adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#Adam optimizer is the very performance optimizer that can perform the SGD(stochastic gradient descent)
#So this SGD updates the weights in order to reduce the loss and error between your predictions and real results
#And loss function computes the difference between the predictions and the real results
#i.e;(accuracy: performance metric) when we have to predict the binary outcome (1/0)
#loss must always be binary_crossentropy otherwise catogorical_crossentropy
#(If there are more than 2 catogories, activation func should be softmax not sigmoid**)


### Training the ANN on the Training set

In [32]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)
#Batch learning is more efficient performant when training a ANN
#i.e instead of comparing ur predictions to the real results one by to one compute and reduce the loss
#give batch wise(batch learning) default size is 32

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.7131 - accuracy: 0.4272
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6191 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5766 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5502 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5195 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5003 - accuracy: 0.7960
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4879 - accuracy: 0.7960
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4749 - accura

## Part 4 - Making the predictions and evaluating the Model

### Predicting the result of a single observation

In [65]:
'''print(ann.predict(sc.transform([[1, 0, 1, 0, 600,1, 40, 3, 60000, 2, 1,1 , 50000]])))
the above gives the probabilty in o/p so
print(ann.predict(sc.transform([[1, 0, 1, 0, 600,1, 40, 3, 60000, 2, 1,1 , 50000]]))) > 0.5
the gives 1 if predicted probabilty is > 0.5'''

#Any input of the predict method must be a 2D array whether it is single or double input
#And we need to enter dummy values(encoded ones) instead of real{eg-France:001}

'print(ann.predict(sc.transform([[1, 0, 1, 0, 600,1, 40, 3, 60000, 2, 1,1 , 50000]])))\nthe above gives the probabilty in o/p so \nprint(ann.predict(sc.transform([[1, 0, 1, 0, 600,1, 40, 3, 60000, 2, 1,1 , 50000]]))) > 0.5\nthe gives 1 if predicted probabilty is > 0.5'

### Predicting the Test set results

In [68]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test), 1)), 1))

63/63 [==============================] - 0s 4ms/step
[[1 0]
 [0 1]
 [1 0]
 ...
 [1 0]
 [1 0]
 [0 0]]


### Making the Confusion Matrix

In [72]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print("\n")
print(accuracy_score(y_test, y_pred))
print("\n")
print(classification_report(y_test,y_pred))

[[924 671]
 [166 239]]


0.5815


              precision    recall  f1-score   support

           0       0.85      0.58      0.69      1595
           1       0.26      0.59      0.36       405

    accuracy                           0.58      2000
   macro avg       0.56      0.58      0.53      2000
weighted avg       0.73      0.58      0.62      2000

